spring:
  application:
    name: ms-shopping-cart

  sql:
    init:
      continue-on-error: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/soat}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /soat-fast-food/v1/ms-shopping-cart

# ===============================
# ACTUATOR
# ===============================
management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /ms-shopping-cart/actuator
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true

# ===============================
# SWAGGER / SPRINGDOC
# ===============================
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# ===============================
# SNS
# ===============================
sns:
  service:
    name: order-created.fifo
    topic:
      arn: ${SNS_TOPIC_ARN:arn:aws:sns:us-east-1:000000000000:sns-ms-shopping-cart}

# ===============================
# AWS
# ===============================
aws:
  access:
    key:
      id: ${AWS_ACCESS_KEY_ID:}
  secret:
    access:
      key: ${AWS_SECRET_ACCESS_KEY:}
  region: ${AWS_REGION:us-east-1}
  account:
    id: ${AWS_ACCOUNT_ID:}


# ===============================
# LOGGING
# ===============================
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    com.zaxxer.hikari: INFO
    com.store.msshoppingcart: INFO
