apiVersion: v1
kind: Secret
metadata:
  name: ms-shopping-cart-secret
  namespace: tech-challenge
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vdGMtcHNxbC1kYi5jMGd6Nm9nNXBheXgudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvc29hdA==
  SPRING_DATASOURCE_USERNAME: dGNhZG1pbg==
  SPRING_DATASOURCE_PASSWORD: VGNUZWNoMjAyNQ==
  API_URL: aHR0cHM6Ly9hcGktdGVjaC1jaGFsbGVuZ2UuY29tL29yZGVyLw==
