apiVersion: v1
kind: Service
metadata:
  name: ms-shopping-cart-service
  namespace: tech-challenge
spec:
  type: ClusterIP
  selector:
    app: ms-shopping-cart-app
  ports:
    - port: 80
      targetPort: 8080
